server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: web-client
          uri: http://localhost:8081/
          predicates:
            - Path=/wesService/**
        - id: rest-client
          uri: http://localhost:8082/
          predicates:
            - Path=/restService/**
